-- Migration: Add record_messages table and avatar_url to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;

CREATE TABLE IF NOT EXISTS public.record_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE NOT NULL,
    entity_type TEXT NOT NULL, -- 'incidencia', 'morosidad', 'gestion'
    entity_id BIGINT NOT NULL,
    content TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE public.record_messages ENABLE ROW LEVEL SECURITY;

-- Policies
-- Authenticated users who can see the entity can see the messages.
DROP POLICY IF EXISTS "record_messages: select active_employee" ON public.record_messages;
CREATE POLICY "record_messages: select active_employee" 
ON public.record_messages FOR SELECT 
TO authenticated 
USING (public.is_active_employee());

DROP POLICY IF EXISTS "record_messages: insert own" ON public.record_messages;
CREATE POLICY "record_messages: insert own" 
ON public.record_messages FOR INSERT 
TO authenticated 
WITH CHECK (public.is_active_employee() AND auth.uid() = user_id);

-- Enable Realtime
ALTER TABLE public.record_messages REPLICA IDENTITY FULL;

-- Add to publication if not already added (usually 'supabase_realtime')
-- Note: This depends on how the publication is named.
-- Trying to add it to supabase_realtime if it exists.
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.record_messages;
  END IF;
END $$;
